id: I8B66CB88
ocr_import_info:
  timestamp: '2023-09-26T07:44:33.629847+00:00'
  batch_id: batch-d83d
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-26 10:54:21.920948+00:00
last_modified: 2023-09-26 10:54:21.920957+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ355761
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ355761
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྭགས་པོ་ཐར་རྒྱན།
  languages:
  - bo
  author: སྒམ་པོ་པ་བསོད་ནམས་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.8491963447961557
  ocr_word_median_confidence_index: 0.90243524
bases:
  I4CZ355915:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ355915
      total_pages: 426
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ355915.txt
    statistics:
      ocr_word_median_confidence_index: 0.90243524
      ocr_word_mean_confidence_index: 0.8491963447961557
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
